---
title: "Health Data Final Project"
author: "R2"
date: "2023-02-16"
output: html_document
---

```{r}
library(readxl)
library(tidyverse)
library(dplyr)
library(tidyselect)
library(lubridate)
library(ggplot2)
```

Load Data Sets:
```{r}
med19= read_excel("Data/Medical 2019.xlsx") %>% 
  janitor:: clean_names()
med20= read_excel("Data/Medical 2020.xlsx") %>% 
  janitor:: clean_names()
rx20= read_excel("Data/Rx 2020.xlsx") %>% 
  janitor:: clean_names()
rx19= read_excel("Data/Rx 2019.xlsx") %>% 
  janitor:: clean_names()
risk20= read_excel("Data/Risk 2020.xlsx") %>% 
  janitor:: clean_names()
risk19=read_excel("Data/Risk 2019.xlsx") %>% 
  janitor:: clean_names()
biom19=read_excel("Data/Biometrics 2019.xlsx") %>% 
  janitor:: clean_names()
biom20=read_excel("Data/Biometricsx 2020.xlsx") %>% 
  janitor:: clean_names()
```


Create Hypertension Dataset:
```{r}
biomed=
  rbind(biom19,biom20)
```

```{r}
ht=
  biomed %>% 
  mutate(
    bps_num= as.numeric(bps)) %>% 
  filter(bps_num >= 130)

summary(ht$bps_num)
```


```{r}
rx_ht_19=
  inner_join(ht,rx19, by = "person")
rx_ht=
  full_join(rx_ht_19, rx20, by= "person")

count=
  htdrugset %>% 
  count(person)

count_ht=
  ht %>% 
  count(person)

count_know=
  anti_join(count_ht,count, by= "person")
```

```{r}
rx_ht_filter=
  rx_ht %>% 
  mutate(rx_ht, group_19= case_when(class.x =="ANTIHYPERTENSIVES"~ 'Y',
                                 class.x== "CALCIUM CHANNEL BLOCKERS" ~ "Y",
                                 class.x== "BETA BLOCKERS" ~"Y",
                                 class.x== "CARDIOVASCULAR AGENTS - MISC." ~ "Y",
                                 TRUE ~ "N" ))

rx_ht_filter_tog=
  mutate(rx_ht_filter, group_20= case_when(class.y =="ANTIHYPERTENSIVES"~ 'Y',
                                 class.y== "CALCIUM CHANNEL BLOCKERS" ~ "Y",
                                 class.y== "BETA BLOCKERS" ~"Y",
                                 class.y== "CARDIOVASCULAR AGENTS - MISC." ~ "Y",
                                 TRUE ~ "N" ))
rx_groups=
  rx_ht_filter_tog %>% 
  distinct(person, bps,age_range.x, bdate.x, from.x, class.x, drug.x, cost.x, bdate.y,from.y, class.y, drug.y, cost.y, group_19, group_20 )

```

```{r}
rx_group_trial=
  mutate(rx_groups, group= case_when(group_19== "Y" & group_20== "Y" ~ 'Consistent',
                                     group_19== "N" & group_20=="Y" ~ 'Started',
                                     group_19=="N" & group_20=="N" ~ "Never",
                                     group_19=="Y" & group_20=="N"~ "Stopped"))
rx_group_counter=
  rx_group_trial %>% 
  group_by(person) %>% 
  count(group)

opp_rx_group_counter=
  rx_group_trial %>% 
  group_by(group) %>% 
  count(person)

rx_merge=
  left_join(count_ht,rx_group_counter,by= 'person')

rx_group_clean=
  rx_group_trial %>% 
  group_by(person) %>% 
  filter(class.x %in% c("ANTIHYPERTENSIVES", "CALCIUM CHANNEL BLOCKERS", "BETA BLOCKERS", "CARDIOVASCULAR AGENTS - MISC.")| class.y %in% c("ANTIHYPERTENSIVES", "CALCIUM CHANNEL BLOCKERS", "BETA BLOCKERS", "CARDIOVASCULAR AGENTS - MISC.")) %>% 
  count(group)
```

```{r}
rx_ht_19=
  rx_ht %>% 
 group_by(person) %>% 
  mutate(group_19 = case_when(
    (any(class.x == "CALCIUM CHANNEL BLOCKERS" | class.x == "CARDIOVASCULAR AGENTS - MISC." | class.x == "ANTIHYPERTENSIVES" | class.x == "BETA BLOCKERS")) ~ "Y", 
  TRUE ~ "N")
  )
```



*BPS Change Over Time*

Joining by person and creating df for person, bps 2019, and bps 2020
```{r}
biometric=
  inner_join(biom19,biom20, by="person")
biometric_bps=
biometric %>% 
  distinct(person, bps.x,bps.y) %>% 
  select(person, bps.x, bps.y)
```

Categorizing changes in blood pressure from 2019-2020
```{r}
biometric_bps_num=
  biometric_bps %>% 
  mutate(bps_19= as.numeric(bps.x),
         bps_20= as.numeric(bps.y))

biometric_bps_change=
  biometric_bps_num %>% 
  mutate(biometric_bps_num, bps_change= case_when(bps_19 < bps_20 ~ 'Higher',
                                     bps_19 > bps_20 ~ 'Lower',
                                     bps_19==bps_20 ~ 'No Change'))
bps_change=
  biometric_bps_change %>% 
  select(person, bps_19, bps_20, bps_change)

bps_counter=
  bps_change %>% 
  count(bps_change)
```

*START HERE*
Merge Attempt

```{r}
biom19 = biom19 %>% drop_na(bps)
biom20 = biom20 %>% drop_na(bps)

bio_merge=
  inner_join(biom19, biom20, by= "person")

bio_merge_2=
  bio_merge %>% 
  mutate(
    bps_19= as.numeric(bps.x)) %>% 
  filter(bps_19 >= 130)

summary(bio_merge_2$bps_19)
```

```{r}
rx19 = rx19 %>% drop_na(class)
rx20 = rx20 %>% drop_na(class)

rx_19_drug=
  rx19 %>% 
  group_by(person) %>%
  mutate(
  group_19 = case_when(
    (any(class == "CALCIUM CHANNEL BLOCKERS"| class == "ANTIHYPERTENSIVES" | class == "BETA BLOCKERS")) ~ "Y", 
  TRUE ~ "N")) %>% 
  distinct(person, group_19)

rx_19_drug %>% group_by(group_19) %>% count()


rx_20_drug=
  rx20 %>% 
  group_by(person) %>%
  mutate(
  group_20 = case_when(
    (any(class == "CALCIUM CHANNEL BLOCKERS"| class == "ANTIHYPERTENSIVES" | class == "BETA BLOCKERS")) ~ "Y", 
  TRUE ~ "N")) %>% 
  distinct(person, group_20)
```

```{r}
rx_merge=
  merge(rx_19_drug, rx_20_drug, by = "person")

rx_grouping=
  rx_grouping %>% 
  mutate(rx_merge, group= case_when(group_19== "Y" & group_20== "Y" ~ 'Consistent',
                                     group_19== "N" & group_20=="Y" ~ 'Started',
                                     group_19=="N" & group_20=="N" ~ "Never",
                                     group_19=="Y" & group_20=="N"~ "Stopped"))

rx_group_counter=
  rx_grouping %>% 
  group_by(group) %>% 
  count(group)
```


```{r}
ht_drug_merge=
  left_join(bio_merge_2, rx_grouping, by= 'person')
```

